obstacle_range: 6.0
raytrace_range: 8.0
footprint: [[0.65, 0.40], [0.65, -0.40], [-0.65, -0.40], [-0.65, 0.40]]
inflation_radius: 1.0
cost_scaling_factor: 1.0

observation_sources: scan
scan:
  data_type: LaserScan
  topic: /base_scan
  marking: true
  clearing: true
