global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  static_map: true
  always_send_full_costmap: true

  plugins:
    - name: static
      type: costmap_2d::StaticLayer
    - name: inflation
      type: costmap_2d::InflationLayer

  static:
    map_topic: /map                     # map_server가 /map 내보내야 함

  inflation:
    enabled: true
    inflation_radius: 1.2
    cost_scaling_factor: 2.5
