local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  transform_tolerance: 0.5
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05
  static_map: false
  always_send_full_costmap: true        # RViz 반영 빨라짐
  footprint_padding: 0.05               # 차체 여유 5cm (선택)

  plugins:
    - name: obstacles
      type: costmap_2d::ObstacleLayer
    - name: inflation
      type: costmap_2d::InflationLayer

  # ⬇⬇⬇ 레이어 별 파라미터는 '이름' 아래로
  obstacles:
    observation_sources: scan
    scan:
      topic: /base_scan                 # Stage sicklaser 토픽
      sensor_frame: base_laser          # 실제 프레임명 다르면 맞춰주세요
      data_type: LaserScan
      marking: true
      clearing: true
      obstacle_range: 8.0
      raytrace_range: 10.0

  inflation:
    enabled: true
    inflation_radius: 1.2               # 회색 띠 반경 크게
    cost_scaling_factor: 2.5            # 작을수록 멀리까지 진하게
